### ISSUE TITLE
这个是什么意思，没看懂

### ISSUE THREAD

**Issue by duoshoumiao** [watermellye/arena#10]
![Screenshot_20230909-192512.jpg](https://github.com/watermellye/arena/assets/94856184/3856beed-ef18-4d56-99a7-a1e716e6610c)

**Comment by watermellye** [comment]
没有搜索到这个报错。一般是说参数数量不对。你可以考虑检查一下opencv的版本。

**Comment by duoshoumiao** [comment]
这个已经解决，谢谢  现在就剩频道不能图文一起发 不会整
