### ISSUE TITLE
有没有办法不用图片跟文字一起发

### ISSUE THREAD

**Issue by duoshoumiao** [watermellye/arena#11]
KOOK频道里面文字跟图片没办法一起发

**Comment by watermellye** [comment]
https://github.com/pcrbot/picfinder_take/blob/main/__init__.py
可以参考这个。

**Comment by duoshoumiao** [comment]
> https://github.com/pcrbot/picfinder_take/blob/main/__init__.py
> 可以参考这个。

我太菜了不会弄，文字可以取消前缀指令，图片的不会😂

**Comment by watermellye** [comment]
由于KOOK和QQ的消息接口不一样，我也并不开发KOOK机器人，因此我不会帮你编写具体的代码示例。
下面是关于我上面发给你的链接的解释。

链接里面是识图插件的实现文字和图片分离方式。简单来说，你需要缓存用户的状态。用户先发送一条指令（例如“搜图”），则将用户（在一定时间内）置于“搜图”状态。此时如果在检测到用户发送了图片，则触发搜图逻辑。反之，如果检测到用户发送了图片，但发现用户并不处于“搜图”状态，则无视此图片。

你可以参考这个逻辑进行实现。

**Comment by duoshoumiao** [comment]
> 由于KOOK和QQ的消息接口不一样，我也并不开发KOOK机器人，因此我不会帮你编写具体的代码示例。
> 下面是关于我上面发给你的链接的解释。
> 
> 链接里面是识图插件的实现文字和图片分离方式。简单来说，你需要缓存用户的状态。用户先发送一条指令（例如“搜图”），则将用户（在一定时间内）置于“搜图”状态。此时如果在检测到用户发送了图片，则触发搜图逻辑。反之，如果检测到用户发送了图片，但发现用户并不处于“搜图”状态，则无视此图片。
> 
> 你可以参考这个逻辑进行实现。

👌
