### ISSUE TITLE
新版QQbug 最新版QQ无法识别截图,老版本可以

### ISSUE THREAD

**Issue by 1529960009** [watermellye/arena#13]
![Image_1714035740451.jpg](https://github.com/watermellye/arena/assets/45947734/eb63bc57-23ff-4f44-8b48-7fb41c3ca887)

**Comment by watermellye** [comment]
根据bot使用的前端（通信端）不一样，可能出现各种问题。有的可以通过修改代码临时解决（例如：将&amp;转为&；删除spec及之后的字段）；有的缺少了token，需要手动拼一段token上去，或者等待通信端更新。

如果您仍未解决此问题，可以在这里附上日志。

**Comment by watermellye** [comment]
https://github.com/Mrs4s/go-cqhttp/issues/2507
