### ISSUE TITLE
找不到指定模块

### ISSUE THREAD

**Issue by XiaoFuOS** [watermellye/arena#3]
什么原因，是没有opencv吗
![1](https://user-images.githubusercontent.com/103229747/176664456-ee06fdfd-b928-458f-8af6-efab0f120afd.png)
![2](https://user-images.githubusercontent.com/103229747/176664472-ea18cb72-e419-44c2-a797-b6193fdd6e90.png)

**Comment by watermellye** [comment]
可能和服务器的操作系统有关。
参考方案：服务器安装一下视图有关的功能
服务器管理器-属性-添加角色和功能-功能-用户界面和基础结构的√桌面体验，安装，重启服务器

**Comment by XiaoFuOS** [comment]
> 可能和服务器的操作系统有关。 参考方案：服务器安装一下视图有关的功能 服务器管理器-属性-添加角色和功能-功能-用户界面和基础结构的√桌面体验，安装，重启服务器

是没有报错了，原来是安装过这个东西，然后电脑重装后忘记重新安装了哈哈哈哈，现在正常使用，但是出现这种是啥意思呢
![1](https://user-images.githubusercontent.com/103229747/176669808-f1db4ab8-3bd4-42fb-8938-69dda3515d25.png)

**Comment by watermellye** [comment]
向pcrdfans查询的逻辑为hoshino作者（咖啡）实现，并非我编写，因此请参考hoshino的issue，或进群询问。
猜测可能和apikey相关，可能是hoshino版本问题，也可能单纯是pcrdfans的问题（可以多试几次）。

**Comment by XiaoFuOS** [comment]
> 向pcrdfans查询的逻辑为hoshino作者（咖啡）实现，并非我编写，因此请参考hoshino的issue，或进群询问。 猜测可能和apikey相关，可能是hoshino版本问题，也可能单纯是pcrdfans的问题（可以多试几次）。

问了，code103是apikey不正确的问题，但pcrdfans不给申请apikey了（哭）

**Comment by watermellye** [comment]
据我所知，还有无apikey，直接通过网页端获取结果的pcrjjc版本。在hoshino群有提供该版本下载。github上有无不清楚。
