### ISSUE TITLE
函数未定义

### ISSUE THREAD

**Issue by XiaoFuOS** [watermellye/arena#4]
![IMG_20220704_110917](https://user-images.githubusercontent.com/103229747/177075167-1f4c32c6-f6c5-4a29-848f-9899babe1cba.jpg)
![Screenshot_2022-07-04-11-08-56-631_com microsoft rdc androidx](https://user-images.githubusercontent.com/103229747/177075187-6d25c959-6095-456c-8fbc-4e284b58534e.jpg)
我好像没有改代码的( ｰ̀εｰ́ )

**Comment by watermellye** [comment]
这部分代码函数为原生hoshino。您的console截图不完整。
猜测原因为hoshino版本不同。
hoshino曾在某个版本将图片载入改为异步（需增加await）
若您使用的是旧版hoshino，请在报错函数中找到注释，去除await；或更新。

**Comment by XiaoFuOS** [comment]
![Screenshot_2022-07-04-21-42-58-597_com microsoft rdc androidx](https://user-images.githubusercontent.com/103229747/177167172-dcd7c0c9-64d2-418a-b754-642bf1dd0dcf.jpg)
HoshinoBot用的是目前更新到的最新版

**Comment by XiaoFuOS** [comment]
> ![Screenshot_2022-07-04-21-42-58-597_com microsoft rdc androidx](https://user-images.githubusercontent.com/103229747/177167172-dcd7c0c9-64d2-418a-b754-642bf1dd0dcf.jpg) HoshinoBot用的是目前更新到的最新版

![Screenshot_2022-07-04-21-46-36-172_com microsoft rdc androidx](https://user-images.githubusercontent.com/103229747/177167803-42f64a24-ff55-490e-9f37-0aa4252deca3.jpg)
是少这几个资源文件的原因吗

**Comment by watermellye** [comment]
是的。这个插件源自HoshinoBot。
相关图片资源（其实是点赞和点踩的图标）原本在[HoshinoBot](https://github.com/Ice-Cirno/HoshinoBot)的[官方群](https://jq.qq.com/?_wv=1027&k=6zyqKSqT)的群文件（不知为何没有直接放在repo里）。
但是群因故炸了几次，新群的群文件已经没有了。你也可以选择随便找个小图标。

**Comment by watermellye** [comment]
更新：作者重新上传了res包。如果需要或者还有其它问题，欢迎来群里玩。
