### ISSUE TITLE
显示爱梅斯未实装

### ISSUE THREAD

**Issue by duoshoumiao** [watermellye/arena#6]
要怎么处理？

**Comment by watermellye** [comment]
该提示显示的直接原因为：您的pcr角色花名册未更新。

arena原作者（暨HoshinoBot作者）将实装的角色的ID范围限定在(1000,1900)。
![image](https://user-images.githubusercontent.com/22909197/205949973-8e91d9ca-73de-4719-b62c-a0a28325888a.png)
在爱梅斯未进入卡池前，其角色ID被设为1900。在进入卡池后，其角色ID被设为1230。

由于本插件能识别的角色根据您的chara列表和res中的角色图标决定，每天会定时同步一次（您也可以通过指令`竞技场更新卡池`来手动同步）。因此您现在要做的是：更新花名册和头像库。

以下是如何更新花名册的简要步骤：

[HoshinoBot](https://github.com/Ice-Cirno/HoshinoBot)的作者同时维护了记录Princess Connect Re:Dive中角色的各种昵称、别称、简称的[兰德索尔花名册](https://github.com/Ice-Cirno/LandosolRoster)。
在新版HoshinoBot中，在`hoshino/modules/priconne/pcr_data_updater.py`中有更新花名册的触发指令（`更新花名册`）。该指令会每日自动触发一次。若（由于网络等问题）无法成功更新，您可以（科学上网），手动打开里面的[网址](https://raw.githubusercontent.com/Ice-Cirno/LandosolRoster/master/_pcr_data.py)，将内容全部复制，替换掉`hoshino/modules/priconne/_pcr_data.py`中的原内容。

以下是如何更新角色头像的简要步骤：

在更新花名册完毕后，在新版HoshinoBot中，在`hoshino/modules/priconne/chara.py`中有多个用于更新头像资源的触发指令。您当前所需要的指令应为“更新头像”。还请您前往该文件手动确认。
