### ISSUE TITLE
函数未定义

### ISSUE THREAD

**Issue by kasuganoyui** [watermellye/arena#7]
![image](https://user-images.githubusercontent.com/104081171/202959921-2a6858c5-d3a4-4aac-b077-c86da04ea693.png)
![GWZAYK(40`TX9~YI3@H}9)2](https://user-images.githubusercontent.com/104081171/202959964-26919550-6c6a-4fdb-8754-24514d16558d.png)

**Comment by watermellye** [comment]
原因不详，请尝试重新克隆本项目。
另，为避免玄学错误，建议修改存放Hoshino项目的文件夹的名字，例如my_bot，QQbot。
![image](https://user-images.githubusercontent.com/22909197/205953260-be4ead79-621a-44d2-9c34-f0bc56ea9ce5.png)
