### ISSUE TITLE
查询后未找到解法，返回值103

### ISSUE THREAD

**Issue by KnightK22** [watermellye/arena#8]
![屏幕截图 2023-02-01 170609](https://user-images.githubusercontent.com/57353187/215999216-7164cb3e-22fe-440c-b18f-9c4ea198178c.png)
请问这个该如何解决呢

**Comment by watermellye** [comment]
这个报错为pcrdfans的服务器的问题。实际上，正是由于pcrdfans提供的API在繁忙时刻非常不稳定，本项目才添加的缓存系统。

**Comment by KnightK22** [comment]
> 这个报错为pcrdfans的服务器的问题。实际上，正是由于pcrdfans提供的API在繁忙时刻非常不稳定，本项目才添加的缓存系统。

好的，谢谢大佬
